version: '3.9'

services:
  seu-manoel-api:
    build:
      context: ./LojaSeuManoelApi
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - loja_net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Senha12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - loja_net

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    entrypoint: >
      /bin/bash -c "
        sleep 20;
        /opt/mssql-tools/bin/sqlcmd -S db -U sa -P Senha12345 -i /docker-entrypoint-initdb.d/init.sql;
      "
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    networks:
      - loja_net

volumes:
  mssql_data:

networks:
  loja_net: